spring:
  application:
    name: position
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/position?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
server:
  port: 8085